[package]

name = "img-dup"
version = "0.3.0"
authors = [ "Austin Bonander <austin.bonander@gmail.com>" ]

[dependencies.time]

git = "https://github.com/rust-lang/time.git"

[dependencies.img_hash]

path = "img_hash/"
