[package]

name = "img-dup"
version = "0.0.1"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]

[dependencies.img_dup_common]
path = "../common"

[dependencies.rgtk]
git = "https://github.com/rust-gnome/gtk"
