[package]

name = "img_dup"
version = "1.0.0"
authors = [ "Austin Bonander <austin.bonander@gmail.com>" ]

[dependencies]
getopts = "*"
log = "*"
rustc-serialize = "*"

[dependencies.common]
path = "../common"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"
