[package]

name = "img-dup-common"
version = "1.0.0"
authors = [ "Austin Bonander <austin.bonander@gmail.com>" ]

[dependencies]
log = "*"
image = "*"
rustc-serialize = "*"
num_cpus = "*"

[dependencies.img-hash]
git = "https://github.com/cybergeek94/img-hash"
features = ["rust-image"]

